In [3]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/Saranmanoharan511/customer-propensity-model/main/customer-propensity-model/cleaned_data.zip", compression="zip")
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
rfm=pd.read_csv("https://raw.githubusercontent.com/Saranmanoharan511/customer-propensity-model/main/customer-propensity-model/rfm_features.zip", compression="zip")

In [5]:
rfm

,CustomerID,Recency,Frequency,Monetary,AvgOrderValue,AvgPurchaseInterval
0,12346.0,326,1,77183.60,77183.600000,0.000000
1,12347.0,2,182,4310.00,23.681319,2.000000
2,12348.0,75,31,1797.24,57.975484,9.400000
3,12349.0,19,73,1757.55,24.076027,0.000000
4,12350.0,310,17,334.40,19.670588,0.000000
...,...,...,...,...,...,...
4333,18280.0,278,10,180.60,18.060000,0.000000
4334,18281.0,181,7,80.82,11.545714,0.000000
4335,18282.0,8,12,178.05,14.837500,10.727273
4336,18283.0,4,721,2045.53,2.837074,0.454167
4337,18287.0,43,70,1837.28,26.246857,2.275362

In [9]:
cutoff_date=df['InvoiceDate'].max()-pd.Timedelta(days=30)

In [10]:
cutoff_date

Timestamp('2011-11-09 12:50:00')

In [15]:
train_df=df[df['InvoiceDate']<=cutoff_date]
future_df=df[df['InvoiceDate']>cutoff_date]

In [16]:
future_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
328431,575317,23544,WALL ART MID CENTURY MODERN,2,2011-11-09 13:12:00,8.25,17402.0,United Kingdom,16.50
328432,575317,21790,VINTAGE SNAP CARDS,12,2011-11-09 13:12:00,0.85,17402.0,United Kingdom,10.20
328433,575317,21791,VINTAGE HEADS AND TAILS CARD GAME,12,2011-11-09 13:12:00,1.25,17402.0,United Kingdom,15.00
328434,575317,22619,SET OF 6 SOLDIER SKITTLES,80,2011-11-09 13:12:00,3.39,17402.0,United Kingdom,271.20
328435,575318,23318,BOX OF 6 MINI VINTAGE CRACKERS,12,2011-11-09 13:17:00,2.49,14921.0,United Kingdom,29.88
...,...,...,...,...,...,...,...,...,...
392687,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
392688,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
392689,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
392690,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
392691,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [17]:
target=future_df.groupby("CustomerID").size()>0
target=target.astype(int)

In [18]:
target

CustomerID
12347.0    1
12349.0    1
12356.0    1
12358.0    1
12362.0    1
          ..
18272.0    1
18273.0    1
18274.0    1
18282.0    1
18283.0    1
Length: 1648, dtype: int64

In [21]:
rfm["Target"]=rfm["CustomerID"].map(target)
rfm["Target"]=rfm['Target'].fillna(0)

In [22]:
rfm

,CustomerID,Recency,Frequency,Monetary,AvgOrderValue,AvgPurchaseInterval,Target
0,12346.0,326,1,77183.60,77183.600000,0.000000,0.0
1,12347.0,2,182,4310.00,23.681319,2.000000,1.0
2,12348.0,75,31,1797.24,57.975484,9.400000,0.0
3,12349.0,19,73,1757.55,24.076027,0.000000,1.0
4,12350.0,310,17,334.40,19.670588,0.000000,0.0
...,...,...,...,...,...,...,...
4333,18280.0,278,10,180.60,18.060000,0.000000,0.0
4334,18281.0,181,7,80.82,11.545714,0.000000,0.0
4335,18282.0,8,12,178.05,14.837500,10.727273,1.0
4336,18283.0,4,721,2045.53,2.837074,0.454167,1.0
4337,18287.0,43,70,1837.28,26.246857,2.275362,0.0

In [24]:
from google.colab import files
rfm.to_csv('final_dataset.csv', index=False)
files.download('final_dataset.csv')